### ISSUE TITLE
Requirement analysis and project management

### ISSUE THREAD

**Issue by Davidliu027** [icpdao/icp#132]
Analysis requirement for my account、DAO organization and voting in below screenshot issues.
And created project board to track progress in https://github.com/icpdao/ICPDAO-Web/projects/1
![image](https://user-images.githubusercontent.com/19386653/118361663-0d36ac80-b5bf-11eb-828a-c23b7668c5cc.png)

**Comment by Davidliu027** [comment]
申请开发 deadline: 2021-04-30 size:5 @fushang318 Requirement analysis and project management

**Comment by fushang318** [comment]
变更 deadline: 2021-05-16

**Comment by fushang318** [comment]
1
