### ISSUE TITLE
Writing and help to correct stories

### ISSUE THREAD

**Issue by Davidliu027** [icpdao/icp#134]
Writing first stories for my account, DAO
Work with UX to correct rest stories.
And elaborate requirements to dev team to make sure they all understand them before dev.
![image](https://user-images.githubusercontent.com/19386653/118361995-40c60680-b5c0-11eb-8618-b0473f33347d.png)
https://github.com/icpdao/ICPDAO-Web/issues

**Comment by Davidliu027** [comment]
申请开发 deadline: 2021-05-07 size: 5 @fushang318 Writing and help to correct stories

**Comment by fushang318** [comment]
deadline: 2021-05-16
