### ISSUE TITLE
【需求+设计】官网首页设计

### ISSUE THREAD

**Issue by nancy919** [icpdao/icp#138]
主要工作：

1、梳理出官网首页必须的核心要素及文字内容；
2、界面布局，并将中文转换成英文；
3、设计UI界面，配图等。
4、与开发进行需求确定。

ux 设计稿：https://www.figma.com/file/LffQCyu0jaU7KyXyU4VldM/ICPDAO-day?node-id=3911%3A9019

**Comment by nancy919** [comment]
申请开发 deadline：2021-06-15 size：2.5 @fushang318

**Comment by fushang318** [comment]
1
