### ISSUE TITLE
ICPDAO high level flow

### ISSUE THREAD

**Issue by bqx619** [icpdao/icp#3]
discuss and determine the operating process of ICPDAO according to #1, and draw the high-level flow chart

**Comment by bqx619** [comment]
申请开发 deadline: 2021-03-17 size: 1 @fushang318

**Comment by bqx619** [comment]
link: https://www.processon.com/view/link/604f5197637689019ddcdda4
flow:
![icpdao high-level flow @bqx619](https://user-images.githubusercontent.com/9692149/111153289-ba477580-85cc-11eb-85f6-450be9a97128.png)

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
1
