### ISSUE TITLE
ICPDAO project introduction preparation

### ISSUE THREAD

**Issue by Davidliu027** [icpdao/icp#8]
Project Logo
Project name/Title: ICPDAO
Project Description: 
Project Website
Project Deliverables: video/Demo/working code
Project Github repository
Project handle: twitter, reddit
Project white paper

**Comment by nancy919** [comment]
**### logo:**
![logo](https://user-images.githubusercontent.com/42829996/112571292-b9abac00-8e22-11eb-89a2-8965be6892b4.png)

**Comment by nancy919** [comment]
**Website**

www.icpdao.co

**Comment by nancy919** [comment]
twitter：ICPDAO
reddit： ICPDAO
YouTube：ICPDAO
gmail：icpdao06@gmail.com

**Comment by Davidliu027** [comment]
Project description
ICPDAO，通过EI(Efficiency Index)机制解决DAO组织贡献决策与量化，基于量化后的贡献铸造Token并自动转化为DEFI的流动性。
**EI机制**
基于博弈与投票解决无效提案，实现组织里人的有效参与、自治与贡献的量化。
**贡献即挖矿**
产生有效贡献即可铸造项目Token，并自动按规则注入DEFI流动性作为永久流动性，贡献者可以在流动池中即时变现，投资者可以在流动池中直接投资。

ICPDAO use EI system to solve governance and quantization problem of DAO contribute , mint project token accordingly and transfer token to Defi liquidity.
**EI system**
Solve the problem of noneffective proposal and voting by a set of rule, make sure the effective involvement of every DAO member, self governance and contribute quantization .
**Contribute is mining**
Valid contribute will mint project token, and add token as perpetual liquidity to Defi pool automatically by pre-defined rule. Contributor can swap fiat token use project token they earned, and investor can buy project token as investment.

![image](https://user-images.githubusercontent.com/19386653/112745671-c411a580-8fdc-11eb-9977-f22e48cce05c.png)

**Comment by georgeliuyu** [comment]
增加一个内容：在AMM的基础上实现ALP（自动化流动性）

**Comment by nancy919** [comment]
**video：**

https://youtu.be/nfudoqMsgDc

https://youtu.be/2DKowjeGiiw

https://youtu.be/7tS6oXfIUTU

https://youtu.be/G7UB1OpUoSU

**Comment by Davidliu027** [comment]
申请开发 deadline: 2021-03-19 size: 1 @georgeliuyu Gather and prepare ICPDAO project info for future use.
